name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2


  # Speech-to-text (with web glue)
  speech_to_text: ^6.6.0
  flutter_web_plugins:
    sdk: flutter

  # HTTP
  http: ^1.2.2
  dio: ^5.5.0

  # UI & Icons
  cupertino_icons: ^1.0.8
  responsive_framework: ^1.4.0

  # Routing & State
  go_router: ^14.2.0
  flutter_riverpod: ^2.5.1

  # Auth/storage/config
  jwt_decoder: ^2.0.1
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.3.2

  # JSON/codegen
  json_annotation: ^4.8.1

  # File upload
  file_picker: ^10.2.3

  # Formatting
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - .env
